### ISSUE TITLE
telegram-purple segfaults when disabling a telegram account on Pidgin

### ISSUE THREAD

**Issue by teemu-kemppainen** [majn/telegram-purple#36] opened 2015-01-19 08:14 UTC
On Pidgin, Accounts -> your telegram account -> Disable causes pidgin to segfault. 

telegram-purple version 0.6.0-4~webupd8~trusty0 installed from ppa:nilarimogard/webupd8
Pidgin version Pidgin 2.10.9 (libpurple 2.10.9)

GDB backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffcfe3cbd0 in ?? () from /usr/lib/purple-2/telegram-purple.so
(gdb) bt
#0  0x00007fffcfe3cbd0 in ?? () from /usr/lib/purple-2/telegram-purple.so
#1  0x00007fffcfe512dc in tglmp_encrypt_send_message () from /usr/lib/purple-2/telegram-purple.so
#2  0x00007fffcfe5610c in ?? () from /usr/lib/purple-2/telegram-purple.so
#3  0x00007fffcfe3db91 in ?? () from /usr/lib/purple-2/telegram-purple.so
#4  0x00007ffff53ab703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff53aace5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff53ab048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff53ab30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff6633447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x000055555558f369 in main (argc=1, argv=0x7fffffffdf08) at /build/buildd/pidgin-2.10.9/./pidgin/gtkmain.c:880
```

**Comment by teemu-kemppainen** [comment] 2015-01-19 08:34
Apparently happens only if telegram-purple for some reason is not connected to the server. Connecting to telegram server "solves" the issue, i.e. removing .telegram-purple folder and restarting Pidgin.

**Comment by majn** [comment] 2015-01-30 19:34
This is a duplicate of https://github.com/majn/telegram-purple/issues/39. I've pointed the current version of the repo to my tgl pull request, which fixes this issue.

If you pull, please make sure that all submodules are correctly synchronised and updated, easiest is to just clone a fresh version of this repository.

**Closed by majn** 2015-01-30 19:34 UTC
Labels: bug, duplicate
