### ISSUE TITLE
pidgin crashes on opening telegram

### ISSUE THREAD

**Issue by 27815733137** [majn/telegram-purple#94] opened 2015-07-28 08:03 UTC
hi guys, I am not very technical but when starting pidgin from terminal on kubuntu
as soon as telegram opens pidgin crashes and i see in terminal
pidgin: tgl/binlog.c:1589: add_log_event: Assertion `rptr == wptr' failed.
Aborted (core dumped)
I also use 27813532358

**Comment by majn** [comment] 2015-07-28 09:38
What version of telegram-purple do you use?

**Comment by 27815733137** [comment] 2015-07-28 10:07
I looked in synaptic because i dont know how else to find version. 
looks like 1.0.0beta

**Comment by majn** [comment] 2015-07-28 10:14
Maybe this issue is already fixed in the newest version, there have been a lot of crash fixes in libtgl since then.

**Comment by 27815733137** [comment] 2015-07-28 10:19
I will try do a reinstall of libtgl and let you know, Thanks for the help so far

**Comment by majn** [comment] 2015-07-28 10:20
That won't help anything if the repository doesn't contain a newer version.

**Comment by 27815733137** [comment] 2015-07-28 10:21
oh my, so how do I get the latest version then?

**Comment by majn** [comment] 2015-07-28 10:27
I don't control the Webup8 repositories, so you either compile it yourself (see README.md) or wait until those are updated.

**Comment by 27815733137** [comment] 2015-07-28 10:29
Cool ty very much, I dont know how to compile things. I will wait. thank you

**Comment by majn** [comment] 2015-08-25 21:43
Seems to be a duplicate of https://github.com/majn/telegram-purple/issues/103

**Closed by majn** 2015-08-25 21:43 UTC
Labels: bug, duplicate

**Comment by 27815733137** [comment] 2015-08-26 09:14
I find that if I keep telegram running as well and delete chats every now and again then pidgin doesnt crash any more. also turned off all login of chats. might be something to do with what telegram puts in pidgin memory
