### ISSUE TITLE
dev-1.3.0: Crash when file transfer happens after server disconnection

### ISSUE THREAD

**Issue by Aketzu** [majn/telegram-purple#250] opened 2016-02-29 15:04 UTC
I got a spurious (bitlbee) crash. 1.3.0+ge8005883ab on libtgl 2.1.0

```
syslog
Feb 29 00:57:59 kelvin telegram-purple[26483]: ping alarm
Feb 29 00:58:03 kelvin telegram-purple[26483]: ping alarm
Feb 29 00:58:14 kelvin telegram-purple[26483]: ping alarm
Feb 29 00:58:14 kelvin telegram-purple[26483]: fail_connection: write_error Broken pipe
Feb 29 00:58:14 kelvin telegram-purple[26483]: Lost connection to server ... 149.154.167.51:80
Feb 29 00:58:14 kelvin telegram-purple[26483]: tgprpl_close()
Feb 29 00:58:15 kelvin telegram-purple[26483]: xfer: 5497087023164226830.ogg
Feb 29 00:58:15 kelvin telegram-purple[26483]: tgprpl_xfer_canceled()

irssi
00:58 [BitlBee] *** prplcb_xfer_dbg 0x0x7f279a0eb200
00:58 [BitlBee] *** ERROR BitlBee crashed! (SIGSEGV received)
```

Feels like tgprpl_xfer_canceled() does some invalid memory access after tgprpl_close()

**Comment by Aketzu** [comment] 2016-03-03 18:27
Had another one. This time bitlbee didn't crash. Just only telegram reconnection.

```
syslog
Mar  3 20:23:42 kelvin telegram-purple[16962]: ping alarm
Mar  3 20:23:44 kelvin telegram-purple[16962]: ping alarm
Mar  3 20:23:44 kelvin telegram-purple[16962]: fail connection: reason: ping timeout
Mar  3 20:23:44 kelvin telegram-purple[16962]: Lost connection to server ... 149.154.167.91:80
Mar  3 20:23:44 kelvin telegram-purple[16962]: tgprpl_close()
Mar  3 20:23:44 kelvin telegram-purple[16962]: xfer: 7259083243007037509.mp4
Mar  3 20:23:44 kelvin telegram-purple[16962]: tgprpl_xfer_canceled()
Mar  3 20:23:50 kelvin telegram-purple[16962]: tgprpl_status_types()
Mar  3 20:23:50 kelvin telegram-purple[16962]: tgprpl_login(): Purple is telling the prpl to connect the account

irssi
20:23 [BitlBee] *** prplcb_xfer_dbg 0x0x7fd5795a7500
20:23 [BitlBee] *** (process:16962): GLib-CRITICAL **: Source ID 494583 was not found when attempting to remove it
20:23 [BitlBee] *** ** (process:16962): WARNING **: (telegram-purple.c:462):update_on_ready: runtime check failed: (P)
20:23 [BitlBee] *** ** (process:16962): CRITICAL **: update_user_handler: assertion 'user->print_name' failed
```

**Comment by BenWiederhake** [comment] 2016-03-04 11:24
As already indicated in dev chat: what BitlBee does there is highly suspicious. First it closes the connection, then it does a transfer? What is the last call supposed to do? How could this possibly work? I believe it's a bug in BitlBee, and it's not possible to prevent things like this reliably by only changing tgp.

**Comment by BenWiederhake** [comment] 2016-03-06 20:32
Oh shit. I fucked up.

Ignore all my comments above, I'm an idiot. The function `tgprpl_close` calls into `tgprpl_xfer_free_all`, which prints out those messages, and causes a call to `tgprpl_xfer_canceled`. So this is not a bug in BitlBee, but sounds like a bug in tgp.

**Comment by Aketzu** [comment] 2016-03-06 21:55
Bitlbee probably just forwards send operations as DCC file sends to irssi which I ignore and just let them timeout. Then the file transfer can be "active" for long periods and if server disconnection happens during that...

**Comment by BenWiederhake** [comment] 2016-03-06 22:06
Meaning tgp has a bug. A bug that has to be triggered by actions I consider unusual, but as you demonstrated: not too unusual.

**Comment by dequis** [comment] 2016-11-13 20:42
>Bitlbee probably just forwards send operations as DCC file sends to irssi which I ignore and just let them timeout. Then the file transfer can be "active" for long periods and if server disconnection happens during that...

This sounds a lot like what I fixed in https://github.com/bitlbee/bitlbee/commit/ea902752503fc5b356d6513911081ec932d804f2 assuming that the crash happens 120 seconds after the DCC request and the telegram account is disconnected during that time. Which, judging by the first debug log of this ticket, is what's happening.

Also, the cancel_local UI op isn't implemented, so that tgprpl_xfer_canceled mentioned in the debug log does nothing.

Pretty sure you can close this.

**Closed** 2016-11-13 21:22 UTC
Labels: bug
