### ISSUE TITLE
Supergroups showed as channels instead of group chats

### ISSUE THREAD

**Issue by gsora** [majn/telegram-purple#395] opened 2017-06-18 16:08 UTC
I'm in a couple of supergroups (both private and public), which are showed as "Telegram Channels" instead of "Telegram Chats".

Pidgin doesn't throw any errors, it just informs me that it's trying to join the chat:

```
(20:00:29) prpl-telegram: tgprpl_chat_join()
(20:00:29) prpl-telegram: type=5
(20:00:29) prpl-telegram: joining channel by id CHAT_ID ...
```

No other meaningful error message are showed.

**Comment by rodneyrod** [comment] 2017-06-19 00:04
I think that's part of the current design, since group chats and supergroups are very different things under the hood.

**Comment by Dagefoerde** [comment] 2017-06-27 13:37
I am seeing the same, with an additional problem:
I cannot enter such a group. That is, I see it in the list and on mobile I am a part of that group and receive all its messages, but no message window is shown in Pidgin, neither when messages arrive nor when I try to enter it.

It appears as if my clicks are just ignored, as nothing happens (no error, no hints, ...); I only found the log lines (as posted above) by accident.

**Comment by majn** [comment] 2017-07-15 14:26
FIY apparently this was caused by a server-side bug, that is now fixed. Multiple people have confirmed that this is issue is now fixed, if you still have this issue please re-open.

**Closed by majn** 2017-07-15 14:26 UTC
