### ISSUE TITLE
Pidgin crashes on account disconnect

### ISSUE THREAD

**Issue by xvitaly** [majn/telegram-purple#248] opened 2016-02-26 14:44 UTC
Pidgin crashes on account disconnect via Account -> Manage Accounts.

Backtrace:
```
GNU gdb (GDB) Fedora 7.10.1-30.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/pidgin...Reading symbols from /usr/bin/pidgin...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: dnf debuginfo-install pidgin-2.10.11-16.fc23.x86_64
(gdb) handle SIGPIPE nostop noprint
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

(Pidgin:3848): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Detaching after fork from child process 3852.
warning: Corrupted shared library list: 0x555555f2d8b0 != 0x5555559556f0
Detaching after fork from child process 3853.
Detaching after fork from child process 3854.
[New Thread 0x7fffc9d4a700 (LWP 3855)]
[New Thread 0x7fffc9549700 (LWP 3856)]

(Pidgin:3848): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(Pidgin:3848): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(Pidgin:3848): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Detaching after fork from child process 3857.
Detaching after fork from child process 3859.
[New Thread 0x7fffb7ffe700 (LWP 3860)]
[New Thread 0x7fffb77fd700 (LWP 3861)]
[New Thread 0x7fffb6ded700 (LWP 3862)]
[New Thread 0x7fffa9845700 (LWP 3863)]
[New Thread 0x7fffa9044700 (LWP 3864)]
[New Thread 0x7fffa8843700 (LWP 3865)]
[Thread 0x7fffa9044700 (LWP 3864) exited]
[Thread 0x7fffb7ffe700 (LWP 3860) exited]
[Thread 0x7fffa9845700 (LWP 3863) exited]
[Thread 0x7fffb6ded700 (LWP 3862) exited]
[Thread 0x7fffb77fd700 (LWP 3861) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd3963f61 in tgls_free_photo () from /usr/lib64/purple-2/telegram-purple.so
(gdb) bt full
#0  0x00007fffd3963f61 in tgls_free_photo () at /usr/lib64/purple-2/telegram-purple.so
#1  0x00007fffd3964339 in tgls_free_message_media () at /usr/lib64/purple-2/telegram-purple.so
#2  0x00007fffd39647e6 in tgls_clear_message () at /usr/lib64/purple-2/telegram-purple.so
#3  0x00007fffd39649b2 in tgls_free_message () at /usr/lib64/purple-2/telegram-purple.so
#4  0x00007fffd3960ef8 in tree_act_ex_message () at /usr/lib64/purple-2/telegram-purple.so
#5  0x00007fffd3968329 in tgl_free_all () at /usr/lib64/purple-2/telegram-purple.so
#6  0x00007fffd394446f in connection_data_free () at /usr/lib64/purple-2/telegram-purple.so
#7  0x00007ffff4dc5286 in _purple_connection_destroy () at /lib64/libpurple.so.0
#8  0x00007ffff4db0e2b in purple_account_disconnect () at /lib64/libpurple.so.0
#9  0x00007ffff33127a5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#10 0x00007ffff3324851 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#11 0x00007ffff332d530 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#12 0x00007ffff332d8ff in g_signal_emit () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff6c4439e in gtk_widget_activate () at /lib64/libgtk-x11-2.0.so.0
#14 0x00007ffff6b2aa7d in gtk_menu_shell_activate_item () at /lib64/libgtk-x11-2.0.so.0
#15 0x00007ffff6b2ae46 in gtk_menu_shell_button_release () at /lib64/libgtk-x11-2.0.so.0
#16 0x00007ffff6b1583d in _gtk_marshal_BOOLEAN__BOXED () at /lib64/libgtk-x11-2.0.so.0
#17 0x00007ffff33127a5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#18 0x00007ffff3324dfe in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff332d122 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#20 0x00007ffff332d8ff in g_signal_emit () at /lib64/libgobject-2.0.so.0
#21 0x00007ffff6c4581c in gtk_widget_event_internal () at /lib64/libgtk-x11-2.0.so.0
#22 0x00007ffff6b13b24 in gtk_propagate_event () at /lib64/libgtk-x11-2.0.so.0
#23 0x00007ffff6b13eeb in gtk_main_do_event () at /lib64/libgtk-x11-2.0.so.0
#24 0x00007ffff676b82c in gdk_event_dispatch () at /lib64/libgdk-x11-2.0.so.0
#25 0x00007ffff3013e3a in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00007ffff30141d0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#27 0x00007ffff30144f2 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#28 0x00007ffff6b12f37 in gtk_main () at /lib64/libgtk-x11-2.0.so.0
#29 0x000055555558fdf7 in main ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 3848] will be killed.

Quit anyway? (y or n) y
```

**Comment by majn** [comment] 2016-02-26 15:09
https://github.com/majn/telegram-purple/issues/248

**Comment by xvitaly** [comment] 2016-02-26 15:30
I don't think it is duplicate. I'm using purple-telegram.x86_64 - 1.2.5-1.fc23.

**Comment by BenWiederhake** [comment] 2016-02-26 15:33
This is not a duplicate of #248 as this IS #248.

Furthermore, he's using 1.2.5-1 from Fedora, which already contains the fix you had in mind, Matthias.

**Comment by majn** [comment] 2016-02-26 18:07
I wanted to link the following two issues:

https://github.com/majn/telegram-purple/issues/238
https://github.com/vysheng/tgl/issues/42

**Comment by majn** [comment] 2016-02-27 13:36
> I don't think it is duplicate of already fixed bug. I'm using purple-telegram.x86_64 - 1.2.5-1.fc23 (latest version from Fedora's main repository).
> This is not a duplicate of #248 as this IS #248.
This is a duplicate of https://github.com/majn/telegram-purple/issues/238 which is not fixed yet, sorry for mixing that up

> Furthermore, he's using 1.2.5-1 from Fedora, which already contains the fix you had in mind, Matthias.
How? https://github.com/BenWiederhake/tgl/commit/3396680933cdc7cf63b5a1acb7f8aad2e6929972 isn't included in the master yet.

**Comment by BenWiederhake** [comment] 2016-02-27 13:57
Whoops, my fault, thought it's already in 1.2.5

**Comment by majn** [comment] 2016-02-27 17:07
Fix is pushed on master

**Closed by majn** 2016-02-27 17:07 UTC
Labels: duplicate
