### ISSUE TITLE
Error in tgl

### ISSUE THREAD

**Issue by SIELA1915** [majn/telegram-purple#353] opened 2017-02-23 18:37 UTC
With telegram-purple last version compiled from source i get an error in tgl when i try to activate the account.
Debug-Log:
```(19:32:44) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
(19:32:44) prpl-telegram: base configuration path: '/Users/eliadmin/.purple/telegram-purple/+41797941520' 
(19:32:44) prpl-telegram: trying global pubkey at /etc/telegram-purple/server.tglpub
(19:32:44) prpl-telegram: read pubkey file: n_len=256 e=65537
(19:32:44) prpl-telegram: using global pubkey
(19:32:44) prpl-telegram: Call to tgl_init failed.
(19:32:44) connection: Connection error on 0x7fb45d062ab0 (reason: 7 description: Unable to sign on as +XXXXXXXXXXX: problem in the underlying library 'tgl'. Please submit a bug report with the debug log.)
```

**Comment by BenWiederhake** [comment] 2017-02-24 21:27
Most definitely a duplicate of https://github.com/majn/telegram-purple/issues/327#issuecomment-274359955 .

For convenience:  
>  Try git checkout dev-1.4.0 after pulling the lastest changes. Don't forget to git submodule update --recursive before building!

Feel free to re-open this issue if this doesn't fix it.

**Closed by BenWiederhake** 2017-02-24 21:27 UTC

**Comment by SIELA1915** [comment] 2017-02-25 00:31
Ok that fixed it (together with getting libgcrypt to work), thx for your help guys!
