### ISSUE TITLE
Big supergroups cause finch to crash (with GDB trace)

### ISSUE THREAD

**Issue by mrkiko** [majn/telegram-purple#293] opened 2016-08-16 19:25 UTC
In a relatively big supergroup, counting actually 3224 participants, telegram-purple and finch have some problems.

In particular, any time the supergroup window gets opened due to incoming messages or manually, finch becomes very unstable.
The plugin seems to disconnect then, crashing once the reconnection happens if the program remains on the same window.

Here is my GDB trace. Thank you for your work and all.

#0  0xb7794a41 in __kernel_vsyscall ()
No symbol table info available.
#1  0xb7151e70 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#2  0xb7153397 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#3  0xb714a9a7 in __assert_fail_base () from /usr/lib/libc.so.6
No symbol table info available.
#4  0xb714aa2b in __assert_fail () from /usr/lib/libc.so.6
No symbol table info available.
#5  0xb177bda9 in tree_insert_peer_by_name (T=0x9619b08, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#6  0xb177bdb7 in tree_insert_peer_by_name (T=0x98415c0, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#7  0xb177bdb7 in tree_insert_peer_by_name (T=0x943e2c0, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#8  0xb177bdb7 in tree_insert_peer_by_name (T=0x9794968, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#9  0xb177bdb7 in tree_insert_peer_by_name (T=0x946aea8, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#10 0xb177bdb7 in tree_insert_peer_by_name (T=0x98850b0, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#11 0xb177bdb7 in tree_insert_peer_by_name (T=0x9767588, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#12 0xb177bdc8 in tree_insert_peer_by_name (T=0x95eeb88, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#13 0xb177bdc8 in tree_insert_peer_by_name (T=0x9752360, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#14 0xb177bdb7 in tree_insert_peer_by_name (T=0x946aaa8, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#15 0xb177bdb7 in tree_insert_peer_by_name (T=0x945d590, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#16 0xb177bdb7 in tree_insert_peer_by_name (T=0x96d1cd8, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#17 0xb177bdb7 in tree_insert_peer_by_name (T=0x9558808, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#18 0xb177bdb7 in tree_insert_peer_by_name (T=0x96c7fe0, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#19 0xb177bdb7 in tree_insert_peer_by_name (T=0x990f978, x=0x992f138,
    y=755479186) at structures.c:83
        c = <optimized out>
        __PRETTY_FUNCTION__ = "tree_insert_peer_by_name"
#20 0xb177e809 in tglp_peer_insert_name (TLS=0x95f0f48, P=0x992f138)
    at structures.c:2445
No locals.
#21 0xb17839e2 in bl_do_user (TLS=0x95f0f48, id=238438421,
    access_hash=0x9b9ece8, first_name=0x96ee1f0 "Alex", first_name_len=4,
    last_name=0x0, last_name_len=0, phone=0x0, phone_len=0, username=0x0,
    username_len=0, photo=0x0, profile_photo=0x0, last_read_in=0x0,
    last_read_out=0x0, bot_info=0x0, flags=<optimized out>) at binlog.c:610
        _U = 0x992f138
        updates = <optimized out>
        __PRETTY_FUNCTION__ = "bl_do_user"
        U = <optimized out>
#22 0xb177eb5e in tglf_fetch_alloc_user (TLS=0x95f0f48, DS_U=0x9b9ec78)
    at structures.c:339
        user_id = {peer_type = 1, peer_id = 238438421,
          access_hash = 7712579149719669150}
        U = 0x992f138
        flags = <optimized out>
        __PRETTY_FUNCTION__ = "tglf_fetch_alloc_user"
#23 0xb17769a5 in channels_get_members_on_answer (TLS=0x95f0f48, q=0x968c078,
    D=0x9676bf0) at queries.c:2890
        DS_CP = 0x9676bf0
        count = 200
        E = <optimized out>
        i = 196
#24 0xb17709c8 in tglq_query_result (TLS=0x95f0f48, id=6318974087104059392)
    at queries.c:479
        save = <optimized out>
        DS = 0x9676bf0
        end = 0xb284ca38 <Response.11036+13368>
        eend = 0xb284ca38 <Response.11036+13368>
        q = 0x968c078
        __PRETTY_FUNCTION__ = "tglq_query_result"
#25 0xb1769d0a in work_rpc_result (c=0x95c5e58, msg_id=6318974090857924609,
    TLS=0x95f0f48) at mtproto-client.c:848
        id = <optimized out>
#26 rpc_execute_answer (TLS=TLS@entry=0x95f0f48, c=c@entry=0x95c5e58,
    msg_id=6318974090857924609) at mtproto-client.c:949
No locals.
#27 0xb176ab78 in process_rpc_message (enc=0xb2849600 <Response.11036>,
    len=<optimized out>, c=0x95c5e58, TLS=0x95f0f48) at mtproto-client.c:1135
        MINSZ = 56
        S = 0x9468cf8
        this_server_time = <optimized out>
        UNENCSZ = 24
        DC = <optimized out>
        l = <optimized out>
        sha1_buffer = "X(\016=\364s\023[\212\340\213\346\177{2\341\016\354\315\t
"
        sha1_buffer = "X(\016=\364s\023[\212\340\213\346\177{2\341\016\354\315\t
"
#28 rpc_execute (TLS=0x95f0f48, c=0x95c5e58, op=2001737565, len=13368)
    at mtproto-client.c:1189
        DC = <optimized out>
        Response_len = <optimized out>
        Response = <error reading variable Response (value requires 16777216 byt
es, which is more than max-value-size)>
        __PRETTY_FUNCTION__ = "rpc_execute"
        o = <optimized out>
        __func__ = "rpc_execute"
#29 0xb175b2b6 in try_rpc_read (c=0x95c5e58) at tgp-net.c:431
        len = 13368
        t = 0
        op = 2001737565
        TLS = 0x95f0f48
#30 try_read (c=0x95c5e58) at tgp-net.c:476
        x = <optimized out>
#31 conn_try_read (arg=0x95c5e58, source=10, cond=PURPLE_INPUT_READ)
    at tgp-net.c:227
        c = 0x95c5e58
#32 0x08065587 in purple_gnt_io_invoke (source=0x97b53a0, condition=G_IO_IN,
    data=0x94125a0) at finch.c:186
        closure = 0x94125a0
        purple_cond = PURPLE_INPUT_READ
#33 0xb7480a1b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#34 0xb7480e09 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#35 0xb74811b9 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#36 0xb742b7fc in gnt_main () at gntmain.c:524
No locals.
#37 0x080569a3 in main (argc=<optimized out>, argv=<optimized out>)
    at finch.c:462

**Comment by BenWiederhake** [comment] 2016-09-02 11:27
This is a duplicate of #224.  We don't know yet why this happens, and why I can't reproduce that.  Like I already mentioned in #224, please send me an invitation link so I can reproduce this issue.

**Closed by BenWiederhake** 2016-09-02 11:27 UTC
