### ISSUE TITLE
Pidgin crashes when too many Telegram messages to open

### ISSUE THREAD

**Issue by robmausser** [majn/telegram-purple#259] opened 2016-03-31 15:20 UTC
Basically I have pdigin on my work machine, but wont open it for weeks.

The Telegram plugin is historical in nature it seems, and wants to present every single message that was written to me in Telegram at once in the time that it was closed, which crashes Pidgin.

It gives an error for the Microsoft Visual C++ Runtime to terminate in an unusual way.

**Comment by majn** [comment] 2016-03-31 15:27
This may be a duplicate of https://github.com/majn/telegram-purple/issues/220

**Comment by robmausser** [comment] 2016-03-31 17:21
It is I just confirmed.

The patch on #220 fixed the issue.

Thanks

**Closed** 2016-03-31 17:33 UTC
Labels: duplicate
