### ISSUE TITLE
Please create proper `make distcheck`-like tarballs

### ISSUE THREAD

**Issue by ikeydoherty** [majn/telegram-purple#200] opened 2015-12-31 16:50 UTC
I've heard that there are complaints the github tarballs "do not work".

When tagging a release, as you're using autotools, use `make distcheck` to produce a *valid* tarball for distribution, which can be attached to the tag's release page via the Edit function.

Look here to see what I mean: https://github.com/solus-project/budgie-desktop/releases

These are suitable for packaging and distribution within other projects then. (Context here is that telegram-purple has been requested within Solus)

**Comment by ikeydoherty** [comment] 2015-12-31 16:52
Also your git tree is very very unclean, you have files that should only be present in a distributed tarball, not a VCS tree. (`.gitignore` and `make clean/distclean` can help here tremendously)

**Comment by BenWiederhake** [comment] 2015-12-31 17:06
What you call "very very unclean" seems to be that users can chouckout the repository, and only need `./configure && make` to build it. If some user tries to build your repo, they would have to install the appropriate versions of autotools, macros for inclusion, etc.

`make distcheck` isn't possible, because this project [doesn't use Automake](https://github.com/majn/telegram-purple/issues/137).

What exactly do you mean with "valid source tarball"? You mean as in verifiable?

**Comment by majn** [comment] 2015-12-31 17:08
Which files are you talking about? The .m4 macros? The XCode Project?

**Comment by ikeydoherty** [comment] 2015-12-31 17:21
I saw `configure.ac` and assumed automake, my bad.

> If some user tries to build your repo, they would have to install the appropriate versions of autotools, macros for inclusion, etc.

This isn't exactly abnormal. Extremely common practice.

> What exactly do you mean with "valid source tarball"? You mean as in verifiable?

A tarball suitable for distribution, known to include all the files it needs so it can be built, and having passed any test-suites if applicable.

The files I'm talking about are the files usually generated during an `autogen` or `autoreconf`, the files that traditionally are shipped in the tarball, not a git repo :)

**Comment by BenWiederhake** [comment] 2015-12-31 17:24
So what exactly are we talking about? The generated files from autotools, right? Those are intentionally there, because we do *not* assume that the user has autotools installed, working, and in the correct version. `master` is intended to be clonable and ready-to-use by the end user.

**Comment by ikeydoherty** [comment] 2015-12-31 17:25
@BenWiederhake sure, I understand that, but what about for inclusion in a distribution? Not going to git clone inside a package build

**Comment by BenWiederhake** [comment] 2015-12-31 17:29
We don't see a difficulty in packaging this for distribution. In fact, including the `configure` script, for example, makes it easy to package it for Debian (my job), and Fedora (I constantly forget his name), so this is the first time I hear about this being a problem.

Even more: If these files are "in the way", isn't it easily possible for you to just call `autoreconf -f` or similar before your packaging steps?

**Comment by BenWiederhake** [comment] 2015-12-31 17:37
Or, to phrase it differently: What exactly would `make distcheck`, or maybe you meant `make distclean`, do?

**Comment by ikeydoherty** [comment] 2015-12-31 17:37
What you tell me and what messages I get, including your README, definitely conflict. Even if I wanted to go the route of generating a Debian-style orig.tar.xz, the instructions are now invalid in the README.

There is more than one cause for confusion in this repo, perhaps updating the README would be most beneficial.

I'll give it a shot from the autogenerated tarball on the tag

**Comment by majn** [comment] 2015-12-31 17:37
> This isn't exactly abnormal. Extremely common practice.

It still kind of defeats the whole purpose of autoconf, which is creating a portable bash script everyone can just execute on any "Unix-like" operating system. 

I believe it would probably make sense if there was some additional form of automation to prepare the source of the repository for redistribution in tar-balls, but we don't really have this automatism right now and it somehow feels that doing it properly would require a build server. At the moment its important to me to not make the build process any harder than it already is, especially not for users that just want to clone it from Github.

As for packaging, I was always under the impression that configure is what packaging depends on. At least thats what the packaging guides for fedora and debian seem to imply.

**Comment by BenWiederhake** [comment] 2015-12-31 17:39
The autogenerated tarball is broken, because github doesn't include the submodules.

Why is the README invalid? Those steps work fine for me. It's literally just `debian/genorigtar.sh && dpkg-buildpackage`, just the `debian` directory is missing because it lives [over there](https://github.com/BenWiederhake/telegram-purple/tree/debian-develop).

**Comment by ikeydoherty** [comment] 2015-12-31 17:42
No I specifically meant `make distcheck`, which produces a tarball, and ensures it actually works, vs `make dist`, which simply produces the tarball. `distcheck` goes the extra mile and ensures all assets are within that tarball, does a build *from that*, vs your local tree, and optionally any test suite.

Re: Automation of tarballs, not *really* tbh. Scripts can do the job quite easily, and I don't mind looking myself.

> Why is the README invalid? Those steps work fine for me. It's literally just debian/genorigtar.sh && dpkg-buildpackage, just the debian directory is missing because it lives over there.

Because the README mentions a non-existent branch in this repo, so yes, it is invalid.

> The autogenerated tarball is broken, because github doesn't include the submodules.

And we're back to square 1. The reason for opening this issue in the first place. Hence suggesting `distcheck`, but obviously now I now you're not using autotools.

So the suggestion would be a simple script to generate a dist-*like* tarball. Could even be just a simple Makefile target

**Comment by BenWiederhake** [comment] 2015-12-31 17:45
Then the README is *not yet* valid, because the `debian-*` branches will get into the @majn repo when 1.2.3 is released.

        The autogenerated tarball is broken, because github doesn't include the submodules.
    And we're back to square 1.

Err, that's a bug with github, not with us. Use git clone, like everyone else.

You want a tarball? So did I. Go to my repo, use the `genorigtar.sh` thing, which is a wrapper around `rawtar`. Or wait a bit, until this process works.

**Comment by ikeydoherty** [comment] 2015-12-31 17:48
> Then the README is not yet valid, because the debian-* branches will get into the @majn repo when 1.2.3 is released.

Right, so it's still not valid *at this moment*.

> Err, that's a bug with github, not with us. Use git clone, like everyone else.

At no point did I say it's your fault. I'm not here to play the blame game, I'm altogether more interested in *helping*. I'm quite happy to write the relevant scripts.

> You want a tarball? So did I. Go to my repo, use the genorigtar.sh thing, which is a wrapper around rawtar. Or wait a bit, until this process works.

Really? Look, I'm more than happy to do the work myself, as I'd still have to to ensure its properly included in my distribution. Doing a git clone and any form of submodule update *inside* a build environment is just wrong. It's isolated from the network for a reason, and all tarballs are verified against a sha256sum.

You're doing yourself no favours whatsoever in attracting contributors.

**Comment by BenWiederhake** [comment] 2015-12-31 17:55
I know that the tar-situation looks bad, that's why there is a way to generate it in a [reproducible](https://wiki.debian.org/ReproducibleBuilds/Howto) way. I never said that you do this in the build environment. It's intended to replace the missing functionality of github to create that tarball.

Sorry if you feel that way, but I don't have the power to convince github to implement that feature correctly.

**Comment by ikeydoherty** [comment] 2015-12-31 17:57
Not a Debian guy, sorry :) 

And I'm not asking to convince GitHub of anything, we both know that the tarballs will stay broken (I use git submodules too, hence the dist tarballs)

Alright, we'll settle on Tarballs-be-broken-deal-with-it.

I guess the last alternative is to create a tarball from the entire cloned/checked out repo and purge the .git's from them to reduce the size?

**Comment by majn** [comment] 2015-12-31 17:57
@ikeydoherty If you can contribute a script for creating that tarball, that would be great. I've got more people complaining about non-working tarballs, its just that we've got hardly any time for that (The Telegram is protocol is really fast-pacing at the moment)

**Comment by ikeydoherty** [comment] 2015-12-31 17:58
Yeah no I can imagine that, alright gimme a few I'll work on something to create a dist-like tarball

**Comment by ikeydoherty** [comment] 2015-12-31 18:00
Fwiw it's kinda my belief that the distributions should be providing the packaging/special-sauce through contributions and not the upstreams directly. I almost die when someone asks me for a PPA for one of my projects.. :p

**Comment by ikeydoherty** [comment] 2015-12-31 18:55
This is taken care of pull request #201

**Comment by BenWiederhake** [comment] 2016-01-07 11:30
I started working on this, using a hardcoded approach. We probably won't change too often about which submodules there are. (Let's hope for the best.)

**Comment by ikeydoherty** [comment] 2016-01-07 12:20
@BenWiederhake I can take another crack on this tonight if you want, or we can collab, or you have something better already? :P

**Comment by BenWiederhake** [comment] 2016-01-07 13:08
Here's something that at least checks whether {git is clean and we're good to go}(https://github.com/BenWiederhake/telegram-purple/tree/dev-origtar).

The idea is:

- [check whether git is okay](https://github.com/BenWiederhake/telegram-purple/tree/dev-origtar)
- go into each `., tgl/, tgl/tl-parse/`, use git archive to produce a tar
- use tar --concatenate or something (it exists, just have to look up the flag) to produce a single tar
- compress with gzip (rather than `*.tar.xz`)
- overwrite the gzip timestamp, then this will alway produce the same output
- use `git describe --tags` to produce a good name.

Not sure how we could collaborate :P
I already know how to do each step thanks to writing `debian/genorigtar.sh` and fixing `debian/rawtar`, so it's just a combinatorial exercise. Also, I'd prefer to put all code into the makefile, as it's just a few commands, and one file less.

**Comment by BenWiederhake** [comment] 2016-01-07 17:22
Have a look [at this implementation](https://github.com/BenWiederhake/telegram-purple/tree/dev-origtar), which:

- works for me
- is pleasingly short, and hopefully less error-prone that the "git archive all" thing.
- produces reproducible builds, as in: if it's the same git commit and the same grep implementation, then no matter the architecture, time, user, whatever, this process will result in a bitwise identical file.
- actually only takes what's in git, so there's no *need* to filter
- since you're asking for an orig-tarball, there also *must not* be any more filtering going on. (Of course it's a different question whether or not certain files should be in the repository. We decided to include certain automatically generated files to make users' lives easier, but that's not absolute. Orig-tarballs should contains everything, that *is* absolute.)

Are there any edge cases I obviously missed? Does this work for you? Is this actually what you need, or did I miss the point?

**Comment by BenWiederhake** [comment] 2016-01-07 19:11
Just as a "diff" against your script:

- `.tar.gz` instead of `.tar.xz`: Call me old-fashioned, but the risk of another "can't use this on my system" is too high for me. Also, gzip has taken a few steps to become reproducible. I'm not so sure about xz.
- Fewer sanity checks. That's because, well, if the user can run `make dist`, he probably already did *some* things correctly, e.g. it's not a bare repository, there probably is write access, etc. However, I added some checks of what I think may happen a few times.
- Ignores non-git files and refuses in case of changes: very intentional, and a good safety measure.

**Comment by BenWiederhake** [comment] 2016-08-17 11:23
Fixed in 1.3.0.  (I forgot to mention this issue in the commit message.)
Specifically, see the official `.orig.tar.gz`.  Or, if you want to create it by yourself: `make dist`.  It's not perfectly reproducible, yet.

**Closed by BenWiederhake** 2016-08-17 11:23 UTC
Labels: enhancement, help wanted, in-pipeline
