### ISSUE TITLE
Receiving "old" messages already read on mobile devices when starting pidgin

### ISSUE THREAD

**Issue by vanitasvitae** [majn/telegram-purple#102] opened 2015-08-19 09:51 UTC
Hi
Im pretty sure, someone has reported this already or the problem is already known, but I couldnt find an issue here.

Everytime I start pidgin and log into my telegram-purple account after a longer period of only using my mobile device to communicate via telegram, I get every single message that was send/received after the last time I logged out from my computer, shown as unread new message.

Is there any way to fix this?

**Comment by majn** [comment] 2015-08-19 10:09
Hi, this is intended behavior to allow you to have a full history of past conversations.

**Comment by vanitasvitae** [comment] 2015-08-19 10:25
Ah okay. Is there any way to optionally disable this?

**Comment by majn** [comment] 2015-08-19 10:29
Not yet, but I can just add it in the next version if there's a need for it.

**Comment by vanitasvitae** [comment] 2015-08-19 10:32
That would be very nice in my opinion :+1:

**Comment by flandolfi** [comment] 2015-11-19 10:13
Hi! Maybe the read messages could be placed directly in the log file (if any) without showing them, and then show only the unread ones. Is it possible? :)

**Comment by vanitasvitae** [comment] 2015-11-19 10:16
That would be nice. Recently I resetted my laptop and when I started Pidgin thr first time, the program completely froze frome the flood of messages.

**Comment by majn** [comment] 2015-11-20 10:54
@vanitasvitae You can already decrease the threshold for fetching old messages to 1 day, this should prevent this kind of issues. Unread messages will no longer be affected from that (in the newest version)

**Comment by BenWiederhake** [comment] 2020-09-27 09:52
Wasn't this already fixed? Either way, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

**Closed by BenWiederhake** 2020-09-27 09:52 UTC
Labels: enhancement
