### ISSUE TITLE
Improve behavior of group chats when disconnecting and re-connecting

### ISSUE THREAD

**Issue by alex3kov** [majn/telegram-purple#434] opened 2017-11-21 07:30 UTC
When account disconnects, there's a message `The account has disconnected and you are no longer in this chat. You will automatically rejoin the chat when the account reconnects.` in a group chat. It stays there even after reconnect/rejoin, which is a bit ambiguous.  
It would be nice to have a message like `You have rejoined the chat`  after account reconnect and successful rejoin.

**Comment by majn** [comment] 2017-11-22 11:49
This seems more like a secondary issue caused by the "disconnect" bug

**Comment by alex3kov** [comment] 2017-11-22 11:56
What is the "disconnect" bug?

**Comment by majn** [comment] 2017-11-22 13:20
https://github.com/majn/telegram-purple/issues/418

**Comment by alex3kov** [comment] 2017-11-22 13:48
I only get disconnects once in a long while.  
I'm not complaining about disconnects themselves - I'm complaining about chat window not informing the user that chat has been rejoined to. Same thing happens if I upnplug LAN cable.

**Comment by majn** [comment] 2017-11-22 21:41
Oh ok, so your issue is mainly a cosmetical issue.

Well I think we could improve the visuals, maybe remove the users when a chat disconnects and add them again on re-connect or something like that. I don't think I'll actually change the messages that Pidgin prints.

**Comment by alex3kov** [comment] 2017-11-27 21:25
> Well I think we could improve the visuals, maybe remove the users when a chat disconnects and add them again on re-connect or something like that. 

> I don't think I'll actually change the messages that Pidgin prints.

So what will the behaviour look like in the end? If chat message `The account has disconnected...` will remain, then it will still be confusing IMO - chat disconnect is communicated to the user in one format (chat message in bold), chat reconnect - in another format (re-appearance of the users list or something else you are planning). Or do you plan on removing `The account has disconnected...` message as well?

**Comment by BenWiederhake** [comment] 2020-09-26 21:39
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.

**Closed by BenWiederhake** 2020-09-26 21:39 UTC
Labels: enhancement
