### ISSUE TITLE
Pidgin crashes on startup

### ISSUE THREAD

**Issue by Sesivany** [majn/telegram-purple#222] opened 2016-01-09 12:21 UTC
Pidgin with telegram plugin (both 1.2.2 and 1.2.4) enabled crashes on startup. It crashes with this output:
pidgin: updates.c:163: tglu_work_update: Assumption „DS_U->message->to_id“ not satisfied.

I'm attaching a debug log.
[debug.txt](https://github.com/majn/telegram-purple/files/83641/debug.txt)

**Comment by BenWiederhake** [comment] 2016-01-09 12:48
Hmm, looks like an actual bug. I'm looking into it.

Can you give us a backtrace? Maybe it contains something interesting.

**Comment by majn** [comment] 2016-01-09 12:50
I've found the reason, apparently its fixed by this commit that is in libtgl upstream, but not in telegram-purple yet: https://github.com/vysheng/tgl/commit/0595b9ddd64807b6f11b1737e964c7767c39812e

**Comment by Sesivany** [comment] 2016-01-09 12:55
Is there any workaround for that? Will removing plugin local data help?

**Comment by majn** [comment] 2016-01-09 12:57
Remove the state file in .purple/telegram-purple/+1234567/state

**Comment by Sesivany** [comment] 2016-01-09 12:59
Great, it works. Thanks a lot.

**Comment by majn** [comment] 2016-01-09 17:36
I've ported the changes back to the stable libtgl branch used for the live, its on dev-1.2.5 right now.

https://github.com/majn/tgl/commit/e03d95bbdfecaec0aaca7dec60644ed9d8aeff08

**Comment by majn** [comment] 2016-01-09 18:23
This was caused by a channel message, if you can guess which type of message it was (or if you still have the old state file) that would be great for testing if the fix really works.

**Comment by majn** [comment] 2016-01-24 16:01
Fixed in 1.2.5

**Closed by majn** 2016-01-24 16:01 UTC
Labels: bug
