### ISSUE TITLE
Messages no longer received after receiving image

### ISSUE THREAD

**Issue by devinlane** [majn/telegram-purple#517] opened 2019-10-15 18:13 UTC
This is using the Adium plugin, version 1.4.2 as compiled by @ksuther. We're seeing an issue where sending an image to an Adium client, whether through Adium or from the official Telegram app, will result in all further messages TO (but not from) that client being dropped. The client must restart in order to receive messages again.

This is a somewhat new issue as earlier versions of the plugin (1.3.0) and service could send and receive images without dropping messages.

**Comment by EionRobb** [comment] 2019-10-15 19:58
Not just happening with Adium

**Comment by BenWiederhake** [comment] 2019-10-15 20:20
Then it apparently affects only Adium and Windows(?), as I can't reproduce the issue :(

Yeah, no idea what's happening. :(

**Comment by devinlane** [comment] 2019-10-15 20:20
I am reproducing this issue with pidgin and telegram-purple.so as well.

**Comment by EionRobb** [comment] 2019-10-15 20:21
@BenWiederhake no, happening on Linux too, and happening with bitlbee

**Comment by ksuther** [comment] 2019-10-15 20:23
I'm seeing the issue here: https://github.com/majn/telegram-purple/blob/master/tgp-msg.c#L1007

It enters `tgl` and then disappears into a maze of callbacks where `tgp_msg_on_loaded_document` is never called to decrement `C->pending`.

**Comment by selectric401** [comment] 2019-10-15 20:28
I'm seeing similar behaviour with Linux -- the error output from bitlbee (3.6, built from source) matches ksuther's description of the issue. Happy to provide any additional logs or other details if needed.

**Comment by Manu311** [comment] 2019-10-17 18:46
I'm running Pidgin on Gentoo and am running on (current master) commit 44a1349bf4c57e8b648dae113ec7cf3bdbde0789 where I'm also experiencing this issue.
Restarting pidgin itself is not required to fix it, just reconnecting the protocol (including a manual disconnect).
I've just recompiled on commit a103df3ff29c55b07203cba58733464ebb00a7e7 (dev-1.4.3) and the result is the same.

Everything worked until a week ago.

**Comment by BenWiederhake** [comment] 2019-10-17 21:04
That explains why I don't see this issue, my machines go to standby / wake up all the time.

So this sounds like a logic error in tgl.  So yeah, someone™ needs to fix tgl's callback hell.

**Comment by The-Compiler** [comment] 2019-10-18 09:36
I tried writing a quick workaround since I'm not interested in the actual image data anyways (using Bitlbee):

```diff
commit 48efab0851c047de83bbaa9a5d99b7817913a7c7 (HEAD -> master)
Author: Florian Bruhin <git@the-compiler.org>
Date:   Fri Oct 18 10:44:01 2019 +0200

    Disable loading of photos

diff --git a/tgp-msg.c b/tgp-msg.c
index f05ad0b..9ec6554 100644
--- a/tgp-msg.c
+++ b/tgp-msg.c
@@ -425,6 +425,11 @@ int tgp_msg_send (struct tgl_state *TLS, const char *message, tgl_peer_id_t to)
 }
 
 static char *tgp_msg_photo_display (struct tgl_state *TLS, const char *filename, int *flags) {
+  if (filename == NULL) {
+    *flags |= PURPLE_MESSAGE_SYSTEM;
+    return g_strdup_printf (_("[unavailable image]"));
+  }
+
   connection_data *conn = TLS->ev_base;
   int img = p2tgl_imgstore_add_with_id (filename);
   if (img <= 0) {
@@ -624,7 +629,7 @@ static void tgp_msg_display (struct tgl_state *TLS, struct tgp_msg_loading *C) {
 
       case tgl_message_media_photo:
         if (M->media.photo) {
-          g_return_if_fail(C->data != NULL);
+          // g_return_if_fail(C->data != NULL);
           text = tgp_msg_photo_display (TLS, C->data, &flags);
         }
         break;
@@ -1004,7 +1009,9 @@ void tgp_msg_recv (struct tgl_state *TLS, struct tgl_message *M, GList *before)
           // when fetching history. TODO: find out the reason for this behavior
           if (M->media.photo) {
             ++ C->pending;
-            tgl_do_load_photo (TLS, M->media.photo, tgp_msg_on_loaded_document, C);
+            // WORKAROUND for https://github.com/majn/telegram-purple/issues/517
+            // tgl_do_load_photo (TLS, M->media.photo, tgp_msg_on_loaded_document, C);
+            tgp_msg_on_loaded_document(TLS, C, TRUE, NULL);
           }
           break;
         }
```

However, I don't see anything for photos at all, not even text... Any idea why?

**Comment by BenWiederhake** [comment] 2019-10-18 21:30
Thanks for the quickfix!  I have absolutely no idea how it's supposed to work.  However, if you make a PR, I can make it so that others can easily use it by specifying `./configure --disable-images` or something.

**Comment by The-Compiler** [comment] 2019-10-20 13:10
I'd like to figure out how to at least print a text (instead of ignoring images completely) before creating a PR with it. Or maybe I'll find the time to track down what the actual issue is - but I have a lot of things on my plate at the moment.

**Comment by Manu311** [comment] 2019-10-20 13:53
I noticed two things in the meantime:
1. My own pictures (sent by Telegram-Desktop/-Mobile) are always displayed
2. I received a forwarded image which worked. But repeating that with other pictures which didn't work themselves, just continued to break pidgin.

**Comment by BenWiederhake** [comment] 2019-10-21 00:29
> I'd like to figure out how to at least print a text (instead of ignoring images completely) before creating a PR with it.

Have a look at `tgp-msg.h`:

    /**
     * Print a special message in the conversation with a peer assuring that special flags are displayed
     */
    void tgp_msg_special_out (struct tgl_state *TLS, const char *msg, tgl_peer_id_t to_id, int flags);

> Or maybe I'll find the time to track down what the actual issue is - but I have a lot of things on my plate at the moment.

Ah, we're all in that situation.  Welcome, I guess! :)

**Comment by beelze** [comment] 2019-11-06 17:26
Some pictures break the chat, some aren't. Hope someone will resolve this issue in the end :-)

**Comment by himselfv** [comment] 2019-11-18 15:29
If you enable TGL logs by setting "TLS->verbosity = E_DEBUG" in ``telegram_purple.c -> tgprpl_login()`` this can be studied in more detail.

It seems that the request fails with ``FLOOD_WAIT_*`` (FLOOD_WAIT_5 in my case). I've had this problem [in other situations](https://github.com/vysheng/tgl/issues/135).

There's an easy temporary patch by removing the ``error_handled = 1;`` from there (see the issue above). All such images should then just fail to load (but not hold up the queue).

The proper fix is to set ``res = 1`` to trigger proper requery, but as the issue above says, it doesn't quite work and I hadn't gotten to the bottom of it. I'll dig a bit more but if anyone has input on that issue, it'll probably help here too.

**Comment by BenWiederhake** [comment] 2019-11-18 18:51
> There's an easy temporary patch by removing the `error_handled = 1;` from there (see the issue above). All such images should then just fail to load (but not hold up the queue).

Would you like to patch it?  You should have write access to this repository.  If you don't want to, I can write/try/push it myself.

> The proper fix is to set res = 1 to trigger proper requery, but as the issue above says, it doesn't quite work and I hadn't gotten to the bottom of it. I'll dig a bit more but if anyone has input on that issue, it'll probably help here too.

That would be great!

**Comment by The-Compiler** [comment] 2019-11-18 21:30
I've tried that workaround, but it has the same issue mine has: There's nothing at all printed when an image arrives. That's slightly better than holding up the queue completely, but also slightly worse, because it leads to silently missing images potentially without ever noticing.

I tried getting something to work with `tgp_msg_special_out` but all I got were segefaults plus no time to debug them :laughing:

**Comment by himselfv** [comment] 2019-11-20 14:23
@The-Compiler: For me it says something like "failed to download picture"

@BenWiederhake: I will if I don't find a solution soon.

So far it looks like simply resending the query doesn't cut it - once Telegram answers with FLOOD_WAIT it considers that particular query answered. Resending it with new ID produces FILEREF_UPGRADE_NEEDED. I thought this is because the whole chain of queries related to the file download is invalidated so I tested a custom download_error() handler which reschedules the whole download (and skips reporting failure for now) but so far it also ends in FILEREF_UPGRADE_NEEDED.

Only certain images are prone to this, but those that are will always fail, even if you send them to your own contact. So maybe this FILEREF_UPGRADE_NEEDED indicates there are now some other fields in the protocol that tgl should mind.

By the way, have you thought about switching to the official [tdlib](https://github.com/tdlib/td)? It at least is supported. Too much work?

**Comment by BenWiederhake** [comment] 2019-11-21 00:49
> By the way, have you thought about switching to the official [tdlib](https://github.com/tdlib/td)? It at least is supported. Too much work?

[Would love to, but noone did it yet.](https://github.com/majn/telegram-purple/issues/480)

I would be perfectly happy with abandoning tgl if you can make it work with tdlib.

**Comment by himselfv** [comment] 2019-12-04 15:45
Current progress:
Looks like the image references used in tgl (inputFileLocation) are deprecated so may not always work. The recommended way is [inputPhotoFileLocation](https://core.telegram.org/api/files). (Which may also grow obsolete but I don't think we care as pidgin only downloads images when first seeing them).

I've adjusted the request to query inputPhotoFileLocation, but this needs file_reference which needs to be taken from Photo part of the multimedia message. The scheme.tl used in tgl has an outdated Photo structure which has no such field.

You can't just add only that field because modern Photo is a different structure, so all the requests/responses which contain Photo are now different structures too (their codes need to be updated), and everything which uses those in turn, and it snowballs.

If I update the schema to [the one currently provided](https://core.telegram.org/schema), custom schema compiler included in the tgl refuses to compile it, though maybe that's fixable.

**Comment by BenWiederhake** [comment] 2019-12-04 21:26
That's an awful problem, and thank you so much for finding it out and describing it in detail.

It also sounds like a lot of work to fix it.  In fact, it sounds about as much work as changing to TDlib #480 … So I would like to ask you to direct your energy in that direction instead, if you're willing to do so.  This would solve basically all problems simultaneously.

Also, don't worry about making it work on all platforms.  I'm sure that once it works "mostly", people will step in and provide the automation needed for their platform.

**Comment by himselfv** [comment] 2019-12-05 08:30
Yeah, it seems that way. But that's too big of an endeavor for me right now. I'll push a fix that handles FLOOD_WAIT but most images still end up with "cannot be downloaded". At least it shouldn't hang.

Note for posterity:
These seem to be unrelated. FLOOD_WAIT_5s are probably simply returned to indicate that the image is still being uploaded. If you forward an already uploaded image, it goes to FILEREF_UPGRADE_NEEDED straight away.

**Comment by rtud** [comment] 2019-12-28 21:04
Same here, running on linux using bitlbee. Looking forward to the fix :)

**Comment by tackleberry61** [comment] 2020-01-30 06:21
I found a workaround of sorts. Opening the web UI seems to make everything work again for all messages after web login, even without logging out. After 'poking it with firefox' I can even receive pictures etc again like nothing was ever wrong in the first place. You don't need to stay logged into firefox for it to keep working.

**Comment by enebo** [comment] 2020-03-16 16:37
I can appreciate wanting to fix this the proper way but I bet every single use who has to restart Pidgin on a nearly daily basis would prefer a simple path with no message ignoring image that causes a FLOOD_WAIT5.  I did not find this issue until last week and I was going crazy trying to understand why telegram would suddenly stop showing output (it took me quite a while to connect it to image sends).

I am going to try and make the error_handled change suggested above and build it manually today as a workaround (for me anyways).

**Comment by r4m0n** [comment] 2020-03-16 18:12
> I can appreciate wanting to fix this the proper way but I bet every single use who has to restart Pidgin on a nearly daily basis would prefer a simple patch with no message ignoring image that causes a FLOOD_WAIT5. I did not find this issue until last week and I was going crazy trying to understand why telegram would suddenly stop showing output (it took me quite a while to connect it to image sends).

A proper fix would be very welcome, but the workaround mentioned above (keeping the telegram web client running in the browser somewhere) seems to be working fine at least. Been keeping it logged in a tab the last month or so and have no issues.

**Comment by enebo** [comment] 2020-03-16 18:16
@r4m0n I am hoping to not do that but it is good to know that it is an effective work-around until this if fixed.

**Comment by Photon89** [comment] 2020-03-24 09:03
I also experience this problem (Pidgin 2.13.0, Arch Linux). The problem also appears with voice messages, not just images. However, it is not 100% reproducible, neither with images nor with voice messages.

**Comment by himselfv** [comment] 2020-03-24 14:53
It's been a while so I'm not 100% sure but I think the quick fix has been pushed to https://github.com/majn/tgl/commits/master ?

It's in telegram-purple/tree/dev-1.4.3 but not in telegram-purple/tree/master .

At least it doesn't crash here, simply complains with "cannot download image".

**Comment by Photon89** [comment] 2020-03-24 16:06
Would be great to have a 1.4.3 release implementing the fix, or at least have it in master (I'd then switch to the git AUR package). Even if the fix doesn't solve the actual problem, it handles the problem in a much better way and reduces the impact on the user experience dramatically.

**Comment by BenWiederhake** [comment] 2020-03-24 23:26
I'm confused.  Sure, I could do a release now, but I don't see any fix there that might affect this?

**Comment by himselfv** [comment] 2020-03-25 07:41
This one: https://github.com/majn/tgl/pull/30  pulled into tgl.

**Comment by BenWiederhake** [comment] 2020-03-25 09:22
Oh!  Sorry, that makes sense.

I'll release a new version soon.

**Comment by BenWiederhake** [comment] 2020-03-25 21:39
Thanks again for reminding me of this :)
[Version 1.4.3](https://github.com/majn/telegram-purple/releases/tag/v1.4.3) seems to be working nicely.

Like @himselfv said, most newly uploaded images will still fail to load with FILEREF_UPGRADE_NEEDED, but fixing this probably requires another change in the schema, so should go into a separate issue.

**Closed by BenWiederhake** 2020-03-25 21:39 UTC
Labels: bug, help wanted

**Comment by Photon89** [comment] 2020-03-26 14:23
Confirm version 1.4.3 works as expected (that is, doesn't crash and shows an error on failed file transfers). Thanks!

**Comment by Foxtaur** [comment] 2020-04-12 21:35
Version 1.4.3 works very well in that it no longer seizes up, and messages continue to be delivered.

However, I noticed that the "loading document or picture failed" message gets posted to the wrong channel.  At least, for me, it appears in my "Saved Messages" channel rather than in the chat with the person who sent an image.

Still better than a soft-lock, though.
