### ISSUE TITLE
telegram-purple does not work in supergroups

### ISSUE THREAD

**Issue by tchncs** [majn/telegram-purple#194] opened 2015-12-28 14:26 UTC
Hi, i get a 

```
71: RPC_CALL_FAIL 400: PEER_ID_INVALID
```
If i try to send something in a "Supergroup"

**Comment by BenWiederhake** [comment] 2015-12-30 09:34
The term "supergroup" is new to me. Is that the result of several groups "merging"?

**Comment by majn** [comment] 2015-12-31 19:08
I can't test this since I'm not member of a super group, you don't happen to know a public one? :)

**Comment by tchncs** [comment] 2016-01-03 11:33
Yes, sorry for the late answer!
[This](https://telegram.me/joinchat/ACVCYzvIz_HvV6Fc3tYaNA) is a german linux "supergroup".

**Comment by BenWiederhake** [comment] 2016-01-03 12:06
Confirmed. Here's how v1.3.0, equivalent to commit 3b3a4eafc2ad8a9df4bb43672c837212399dc63a, looks like:

---

![bildschirmfoto_2016-01-03_13-00-43](https://cloud.githubusercontent.com/assets/2690845/12078652/7ec9c0d4-b21a-11e5-9cd0-1445aabfb46c.png)

---

Here's how it's displayed in pidgin, German localization:

---

![bildschirmfoto_2016-01-03_13-01-27](https://cloud.githubusercontent.com/assets/2690845/12078658/95657266-b21a-11e5-84dc-6ddf5319a930.png)

**Comment by majn** [comment] 2016-01-03 21:36
Super-groups seem to be implemented as some special-case of channels, so this one probably wait until channel support is completed.

**Comment by sewi-cpan** [comment] 2016-01-14 10:57
No messages arrive in supergroups.

**Comment by majn** [comment] 2016-01-14 11:25
From the telegram blogpost about super groups.

> Please note that you need the latest version of Telegram to access a supergroup. You may want to wait a little bit before upgrading your groups so that the update rolls out to all Telegram users, and they can see their groups.

Read: they are not implemented in a backwards compatible way and you'll have to wait until I found a way to correctly implement them.

**Comment by burzum0** [comment] 2016-01-22 16:45
Any solution?

Still Don't work in supergroups

**Comment by rodneyrod** [comment] 2016-01-24 20:16
Anything we can do to help @majn?

**Comment by majn** [comment] 2016-01-24 21:02
Unless you implement the feature on dev-1.3.0 and create a pull request not much :P

**Comment by rodneyrod** [comment] 2016-02-01 05:31
@majn Well my programming experience is pretty average, but if you guys need any donations I'm more than willing to throw some your way.

**Comment by majn** [comment] 2016-02-20 10:55
This issue is part of feature #122 since supergroups are implemented as a specialized form of channels.

**Comment by BenWiederhake** [comment] 2016-08-17 11:27
Closing this, as 1.3.0 should support supergroups and channels.  If there are any issues, please open a new issue.

**Closed by BenWiederhake** 2016-08-17 11:27 UTC
Labels: enhancement, in-pipeline
