### ISSUE TITLE
autocomplete mentions

### ISSUE THREAD

**Issue by robsonsobral** [majn/telegram-purple#229] opened 2016-01-27 12:12 UTC
Hi!

Thank you for the plugin!

Is it possible to offer an autocomplete after to type `@`? I don't even know if Pidgin supports it.

Thank you!

**Comment by BenWiederhake** [comment] 2016-02-20 14:47
I don't think telegram-purple can even detect whether this happens, so I don't think it's possible.

However, you can already autocomplete existing names, e.g. "Matthias Jentsch" in the dev chat.

**Comment by robsonsobral** [comment] 2016-02-21 14:15
Thanks, @BenWiederhake , but... Dev Chat?

**Comment by majn** [comment] 2016-02-21 14:25
> but... Dev Chat?
You can autocomplete usernames in any pidgin group chats by pressing tab. The problem is just that the username is different to the @Username 

There is an autocomplete-signal emitted that can eventually be used to implement own autocompletion, but I haven't tested that yet.

**Comment by robsonsobral** [comment] 2016-02-22 01:35
Thanks, @majn !

**Comment by BenWiederhake** [comment] 2020-09-27 09:39
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.
Of course, Pull Requests are still very much welcome!

**Closed by BenWiederhake** 2020-09-27 09:39 UTC
Labels: enhancement
