### ISSUE TITLE
Conversation window pops-up even when channel should be silent

### ISSUE THREAD

**Issue by HeikoTietze** [majn/telegram-purple#372] opened 2017-04-09 09:07 UTC
Running Pidgin with telegram-purple from AUR on Arch/LXQt/Kwin/Breeze, I face the problem of conversation windows unwantedly popping up. Played around with the various settings including the message notification plugin but my channel settings are not respected as known from the Android app. What can I do?

**Comment by majn** [comment] 2017-04-09 11:13
What do you mean by unwantedly popping up. Receiving messages?

**Comment by HeikoTietze** [comment] 2017-04-09 21:16
Yes, on new messages whether addressed to me or not pop-up the conversation window.

**Comment by majn** [comment] 2017-04-09 21:18
Thats regular pidgin behavior. Go to the chat settings and make the chat "persistent", then it will receive all messages in the background unless you open it.

**Comment by HeikoTietze** [comment] 2017-04-09 21:21
Could you please explain what "chat settings" mean. Don't find those in my configuration.

**Comment by majn** [comment] 2017-04-10 08:45
Its a setting on the chat itself

**Comment by majn** [comment] 2017-11-23 15:08
I assume the problem is now fixed. Otherwise re-open it

**Closed by majn** 2017-11-23 15:08 UTC

**Comment by sherpya** [comment] 2019-10-24 17:52
it does not work for me, I have persistent option checked and new messages on the channel make pidgin open the chat window
