### ISSUE TITLE
spectrum: assertion failed: purple_account_is_connected(account)

### ISSUE THREAD

**Issue by thundergreen** [majn/telegram-purple#286] opened 2016-06-30 08:50 UTC
Hi guys. again I tried to setup telegram transport but failed. I found this error message in my logs:

6902: 2016-06-30 10:40:58,069 ERROR backend: g_log xmlnode_get_child_with_namespace: assertion 'parent != NULL' failed  
7523: 2016-06-30 10:43:47,976 ERROR backend: g_log xmlnode_get_child_with_namespace: assertion 'parent != NULL' failed  
7523: 2016-06-30 10:43:49,228 ERROR backend: g_log purple_account_set_public_alias: assertion 'purple_account_is_connected(account)' failed  
7523: 2016-06-30 10:43:49,721 ERROR backend: g_log purple_account_set_public_alias: assertion 'purple_account_is_connected(account)' failed    

Somone here to help me out?

**Comment by thundergreen** [comment] 2016-06-30 09:24
Here full LOG..oot@osmc:/var/lib/spectrum2# spectrum2_manager telegram.emevth.no-ip.biz start                                                                                                               
root@osmc:/var/lib/spectrum2# tail -f  /var/log/spectrum2/telegram.emevth.no-ip.biz/backends/backend-1.log                                                                                    
15199: 2016-06-30 11:21:05,217 INFO  libpurple: proxy:Connection in progress                                                                                                                  
15199: 2016-06-30 11:21:05,220 INFO  libpurple: util:Writing file prefs.xml to directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                         
15199: 2016-06-30 11:21:05,220 INFO  libpurple: util:Writing file /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml                                                                      
15199: 2016-06-30 11:21:06,683 INFO  libpurple: status:The attribute "message" on the status "Do not disturb" is not supported.                                                               
15199: 2016-06-30 11:21:06,683 ERROR backend: g_log purple_account_set_public_alias: assertion 'purple_account_is_connected(account)' failed                                                  
15199: 2016-06-30 11:21:06,684 INFO  libpurple: util:Writing file accounts.xml to directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                      
15199: 2016-06-30 11:21:06,684 INFO  libpurple: util:Writing file /var/lib/spectrum2/telegram.emevth.no-ip.biz/accounts.xml                                                                   
15199: 2016-06-30 11:21:07,381 INFO  libpurple: prpl-telegram:Response_len = 652                                                                                                              
15199: 2016-06-30 11:21:07,382 INFO  libpurple: prpl-telegram:rpc_execute: state = 2                                                                                                          
15199: 2016-06-30 11:21:35,573 INFO  libpurple: prpl-telegram:writing packet: total_len = 99, len = 376                                                                                       
15308: 2016-06-30 11:22:58,419 INFO  backend: Setting libpurple plugins directory to: ./plugins                                                                                               
15308: 2016-06-30 11:22:58,419 INFO  backend: Setting libpurple cacerts directory to: ./ca-certs                                                                                              
15308: 2016-06-30 11:22:58,419 INFO  backend: Setting libpurple user directory to: /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                               
15308: 2016-06-30 11:22:58,420 INFO  backend: Will use glib based event loop                                                                                                                  
15308: 2016-06-30 11:22:58,420 INFO  libpurple: prefs:Reading /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml                                                                          
15308: 2016-06-30 11:22:58,421 INFO  libpurple: prefs:Reading /etc/purple/prefs.xml                                                                                                           
15308: 2016-06-30 11:22:58,426 INFO  libpurple: dbus:Failed to get connection: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11                                                  
15308: 2016-06-30 11:22:58,426 INFO  libpurple: plugins:probing /usr/lib/purple-2/libzephyr.so                                                                                                
15308: 2016-06-30 11:22:58,431 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmsn.so                                                                                                   
15308: 2016-06-30 11:22:58,438 INFO  libpurple: plugins:probing /usr/lib/purple-2/liboscar.so                                                                                                 
15308: 2016-06-30 11:22:58,449 INFO  libpurple: plugins:/usr/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURP
LE_INIT_PLUGIN() macro?                                                                                                                                                                       
15308: 2016-06-30 11:22:58,449 INFO  libpurple: plugins:probing /usr/lib/purple-2/libaim.so                                                                                                   
15308: 2016-06-30 11:22:58,456 INFO  libpurple: plugins:probing /usr/lib/purple-2/dbus-example.so                                                                                             
15308: 2016-06-30 11:22:58,457 INFO  libpurple: plugins:probing /usr/lib/purple-2/libwhatsapp.so                                                                                              
15308: 2016-06-30 11:22:58,576 INFO  libpurple: plugins:probing /usr/lib/purple-2/joinpart.so                                                                                                 
15308: 2016-06-30 11:22:58,577 INFO  libpurple: plugins:probing /usr/lib/purple-2/tcl.so                                                                                                      
15308: 2016-06-30 11:22:58,665 INFO  libpurple: plugins:probing /usr/lib/purple-2/libxmpp.so                                                                                                  
15308: 2016-06-30 11:22:58,673 INFO  libpurple: plugins:probing /usr/lib/purple-2/libskypeweb.so                                                                                              
15308: 2016-06-30 11:22:58,678 INFO  libpurple: plugins:probing /usr/lib/purple-2/libyahoo.so                                                                                                 
15308: 2016-06-30 11:22:58,683 INFO  libpurple: plugins:probing /usr/lib/purple-2/libhangouts.so                                                                                              
15308: 2016-06-30 11:22:58,699 INFO  libpurple: plugins:probing /usr/lib/purple-2/libbonjour.so                                                                                               
15308: 2016-06-30 11:22:58,706 INFO  libpurple: plugins:probing /usr/lib/purple-2/libirc.so                                                                                                   
15308: 2016-06-30 11:22:58,710 INFO  libpurple: plugins:probing /usr/lib/purple-2/libymsg.so                                                                                                  
15308: 2016-06-30 11:22:58,712 INFO  libpurple: plugins:/usr/lib/purple-2/libymsg.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPL
E_INIT_PLUGIN() macro?                                                                                                                                                                        
15308: 2016-06-30 11:22:58,712 INFO  libpurple: plugins:probing /usr/lib/purple-2/log_reader.so                                                                                               
15308: 2016-06-30 11:22:58,713 INFO  libpurple: plugins:probing /usr/lib/purple-2/libsimple.so                                                                                                
15308: 2016-06-30 11:22:58,715 INFO  libpurple: plugins:probing /usr/lib/purple-2/libnovell.so                                                                                                
15308: 2016-06-30 11:22:58,719 INFO  libpurple: plugins:probing /usr/lib/purple-2/libyahoojp.so                                                                                               
15308: 2016-06-30 11:22:58,722 INFO  libpurple: plugins:probing /usr/lib/purple-2/libicq.so                                                                                                   
15308: 2016-06-30 11:22:58,724 INFO  libpurple: plugins:probing /usr/lib/purple-2/nss-prefs.so                                                                                                
15308: 2016-06-30 11:22:58,752 INFO  libpurple: plugins:probing /usr/lib/purple-2/libsametime.so                                                                                              
15308: 2016-06-30 11:22:58,759 INFO  libpurple: plugins:/usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.                                        
15308: 2016-06-30 11:22:58,759 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmxit.so                                                                                                  
15308: 2016-06-30 11:22:58,763 INFO  libpurple: prpl-loubserp-mxit:Loading MXit libPurple plugin...                                                                                           
15308: 2016-06-30 11:22:58,763 INFO  libpurple: plugins:probing /usr/lib/purple-2/ssl.so                                                                                                      
15308: 2016-06-30 11:22:58,764 INFO  libpurple: plugins:probing /usr/lib/purple-2/autoaccept.so                                                                                               
15308: 2016-06-30 11:22:58,766 INFO  libpurple: plugins:probing /usr/lib/purple-2/telegram-purple.so                                                                                          
15308: 2016-06-30 11:22:58,801 INFO  libpurple: plugins:probing /usr/lib/purple-2/libmyspace.so                                                                                               
15308: 2016-06-30 11:22:58,803 INFO  libpurple: plugins:probing /usr/lib/purple-2/libjabber.so                                                                                                
15308: 2016-06-30 11:22:58,805 INFO  libpurple: plugins:/usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PUR
PLE_INIT_PLUGIN() macro?                                                                                                                                                                      
15308: 2016-06-30 11:22:58,805 INFO  libpurple: plugins:probing /usr/lib/purple-2/offlinemsg.so                                                                                               
15308: 2016-06-30 11:22:58,806 INFO  libpurple: plugins:probing /usr/lib/purple-2/ssl-nss.so                                                                                                  
15308: 2016-06-30 11:22:58,810 INFO  libpurple: plugins:probing /usr/lib/purple-2/newline.so                                                                                                  
15308: 2016-06-30 11:22:58,811 INFO  libpurple: plugins:probing /usr/lib/purple-2/statenotify.so                                                                                              
15308: 2016-06-30 11:22:58,813 INFO  libpurple: plugins:probing /usr/lib/purple-2/libfacebook.so                                                                                              
15308: 2016-06-30 11:22:58,819 INFO  libpurple: plugins:probing /usr/lib/purple-2/libgg.so                                                                                                    
15308: 2016-06-30 11:22:58,821 INFO  libpurple: plugins:probing /usr/lib/purple-2/buddynote.so                                                                                                
15308: 2016-06-30 11:22:58,823 INFO  libpurple: plugins:probing /usr/lib/purple-2/idle.so                                                                                                     
15308: 2016-06-30 11:22:58,824 INFO  libpurple: plugins:probing /usr/lib/purple-2/psychic.so                                                                                                  
15308: 2016-06-30 11:22:58,854 INFO  libpurple: util:Reading file xmpp-caps.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                   
15308: 2016-06-30 11:22:58,854 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/xmpp-caps.xml does not exist (this is not necessarily an error)                        
15308: 2016-06-30 11:22:58,855 INFO  libpurple: jabber:creating hash tables for data objects                                                                                                  
15308: 2016-06-30 11:22:58,855 INFO  libpurple: gg:Loading Gadu-Gadu protocol plugin with libgadu 1.12.0...                                                                                   
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/offline changed, scheduling save.                                                                                 
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/available changed, scheduling save.                                                                               
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/invisible changed, scheduling save.                                                                               
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/away changed, scheduling save.                                                                                    
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/extended_away changed, scheduling save.                                                                           
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/idle changed, scheduling save.                                                                                    
15308: 2016-06-30 11:22:58,856 INFO  libpurple: prefs:/purple/status/scores/offline_msg changed, scheduling save.                                                                             
15308: 2016-06-30 11:22:58,856 INFO  libpurple: util:Reading file accounts.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                    
15308: 2016-06-30 11:22:58,856 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/accounts.xml does not exist (this is not necessarily an error)                         
15308: 2016-06-30 11:22:58,856 INFO  libpurple: util:Reading file status.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                      
15308: 2016-06-30 11:22:58,856 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/status.xml does not exist (this is not necessarily an error)                           
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificateVerifier x509, singleuse requested but not found.                                                                      
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificateVerifier singleuse registered                                                                                          
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificatePool x509, ca requested but not found.                                                                                 
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.                                                                                   
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate/x509/ca:Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.                            
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate/x509/ca:Init failed, probably because a dependency is not yet registered. It has been deferred to later.                          
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificatePool ca registered                                                                                                     
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificatePool x509, tls_peers requested but not found.                                                                          
15308: 2016-06-30 11:22:58,857 INFO  libpurple: certificate:CertificatePool tls_peers registered                                                                                              
15308: 2016-06-30 11:22:58,858 INFO  libpurple: certificate:CertificateVerifier x509, tls_cached requested but not found.                                                                     
15308: 2016-06-30 11:22:58,858 INFO  libpurple: certificate:CertificateVerifier tls_cached registered                                                                                         
15308: 2016-06-30 11:22:58,858 INFO  libpurple: prefs:/purple/logging/format changed, scheduling save.                                                                                        
15308: 2016-06-30 11:22:58,858 INFO  libpurple: prefs:/purple/logging/format changed, scheduling save.                                                                                        
15308: 2016-06-30 11:22:58,863 INFO  libpurple: prefs:/purple/proxy/type changed, scheduling save.                                                                                            
15308: 2016-06-30 11:22:58,863 INFO  libpurple: prefs:/purple/proxy/host changed, scheduling save.                                                                                            
15308: 2016-06-30 11:22:58,863 INFO  libpurple: prefs:/purple/proxy/port changed, scheduling save.                                                                                            
15308: 2016-06-30 11:22:58,863 INFO  libpurple: prefs:/purple/proxy/username changed, scheduling save.                                                                                        
15308: 2016-06-30 11:22:58,863 INFO  libpurple: prefs:/purple/proxy/password changed, scheduling save.                                                                                        
15308: 2016-06-30 11:22:58,871 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: Enabled                                                                                 
15308: 2016-06-30 11:22:58,871 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: Enabled                                                                                   
15308: 2016-06-30 11:22:58,871 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: Enabled                                                                                    
15308: 2016-06-30 11:22:58,871 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: Enabled                                                                                    
15308: 2016-06-30 11:22:58,871 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: Enabled                                                                                      
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: Disabled                                                                                
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: Enabled                                                                                   
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: Enabled                                                                                      
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                  
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                    
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: Enabled                                                                                        
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_RC4_128_SHA: Enabled                                                                                          
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: Enabled                                                                                     
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA: Enabled                                                                                        
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_AES_128_CBC_SHA: Enabled                                                                                        
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: Enabled                                                                                     
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled                                                                                  
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA: Disabled                                                                                  
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA: Enabled                                                                                        
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_AES_256_CBC_SHA: Disabled                                                                                       
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: Enabled                                                                                     
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled                                                                                  
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA: Disabled                                                                                  
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                      
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                      
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_RC4_128_SHA: Disabled                                                                                           
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA: Disabled                                                                                    
15308: 2016-06-30 11:22:58,872 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_AES_128_CBC_SHA: Disabled                                                                                      
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA: Disabled                                                                                    
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_AES_256_CBC_SHA: Disabled                                                                                      
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                   
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                     
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_RC4_128_SHA: Disabled                                                                                        
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_RC4_128_SHA: Disabled                                                                                          
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_128_GCM_SHA256: Disabled                                                                                        
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_128_CBC_SHA: Enabled                                                                                            
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_128_CBC_SHA256: Disabled                                                                                        
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled                                                                                      
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_256_CBC_SHA: Enabled                                                                                            
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_AES_256_CBC_SHA256: Disabled                                                                                        
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled                                                                                      
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_SEED_CBC_SHA: Disabled                                                                                              
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                     
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_3DES_EDE_CBC_SHA: Disabled                                                                                          
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_RC4_128_SHA: Disabled                                                                                               
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_RC4_128_MD5: Disabled                                                                                               
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_DHE_RSA_WITH_DES_CBC_SHA: Disabled                                                                                           
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_DHE_DSS_WITH_DES_CBC_SHA: Disabled                                                                                           
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - SSL_RSA_FIPS_WITH_DES_CBC_SHA: Disabled                                                                                          
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_DES_CBC_SHA: Disabled                                                                                               
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT1024_WITH_RC4_56_SHA: Disabled                                                                                     
15308: 2016-06-30 11:22:58,873 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA: Disabled                                                                                    
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT_WITH_RC4_40_MD5: Disabled                                                                                         
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5: Disabled                                                                                     
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_ECDHE_ECDSA_WITH_NULL_SHA: Disabled                                                                                          
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_ECDHE_RSA_WITH_NULL_SHA: Disabled                                                                                            
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_ECDH_RSA_WITH_NULL_SHA: Disabled                                                                                             
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_ECDH_ECDSA_WITH_NULL_SHA: Disabled                                                                                           
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_NULL_SHA: Disabled                                                                                                  
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_NULL_SHA256: Disabled                                                                                               
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - TLS_RSA_WITH_NULL_MD5: Disabled                                                                                                  
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - SSL_CK_RC4_128_WITH_MD5: Disabled                                                                                                
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - SSL_CK_RC2_128_CBC_WITH_MD5: Disabled                                                                                            
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - SSL_CK_DES_192_EDE3_CBC_WITH_MD5: Disabled                                                                                       
15308: 2016-06-30 11:22:58,874 INFO  libpurple: nss:Cipher - SSL_CK_DES_64_CBC_WITH_MD5: Disabled                                                                                             
15308: 2016-06-30 11:22:58,875 INFO  libpurple: nss:Cipher - SSL_CK_RC4_128_EXPORT40_WITH_MD5: Disabled                                                                                       
15308: 2016-06-30 11:22:58,875 INFO  libpurple: nss:Cipher - SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5: Disabled                                                                                   
15308: 2016-06-30 11:22:58,875 INFO  libpurple: nss:TLS supported versions: 0x0300 through 0x0303                                                                                             
15308: 2016-06-30 11:22:58,875 INFO  libpurple: nss:TLS versions allowed by default: 0x0300 through 0x0301                                                                                    
15308: 2016-06-30 11:22:58,875 INFO  libpurple: nss:Changed allowed TLS versions to 0x0300 through 0x0303                                                                                     
15308: 2016-06-30 11:22:58,875 INFO  libpurple: certificate:CertificateScheme x509 requested but not found.                                                                                   
15308: 2016-06-30 11:22:58,875 INFO  libpurple: certificate:CertificateScheme x509 registered                                                                                                 
15308: 2016-06-30 11:22:58,875 INFO  libpurple: util:Reading file smileys.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                     
15308: 2016-06-30 11:22:58,875 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/smileys.xml does not exist (this is not necessarily an error)                          
15308: 2016-06-30 11:22:58,875 INFO  libpurple: stun:using server                                                                                                                             
15308: 2016-06-30 11:22:58,876 INFO  libpurple: util:Reading file blist.xml from directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                       
15308: 2016-06-30 11:22:58,876 INFO  libpurple: util:File /var/lib/spectrum2/telegram.emevth.no-ip.biz/blist.xml does not exist (this is not necessarily an error)                            
15308: 2016-06-30 11:22:58,876 INFO  libpurple: prefs:Reading /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml                                                                          
15308: 2016-06-30 11:22:58,876 INFO  libpurple: prefs:Reading /etc/purple/prefs.xml                                                                                                           
15308: 2016-06-30 11:22:58,876 INFO  libpurple: prefs:/purple/away/away_when_idle changed, scheduling save.                                                                                   
15308: 2016-06-30 11:22:58,876 INFO  libpurple: prefs:/purple/logging/log_ims changed, scheduling save.                                                                                       
15308: 2016-06-30 11:22:58,876 INFO  libpurple: prefs:/purple/logging/log_chats changed, scheduling save.                                                                                     
15308: 2016-06-30 11:22:59,867 INFO  libpurple: util:requesting to fetch a URL                                                                                                                
15308: 2016-06-30 11:22:59,867 INFO  libpurple: dnsquery:Performing DNS lookup for 192.168.1.1                                                                                                
15308: 2016-06-30 11:22:59,867 INFO  libpurple: dnsquery:IP resolved for 192.168.1.1                                                                                                          
15308: 2016-06-30 11:22:59,867 INFO  libpurple: proxy:Attempting connection to 192.168.1.1                                                                                                    
15308: 2016-06-30 11:22:59,867 INFO  libpurple: proxy:Connecting to 192.168.1.1:60000 with no proxy                                                                                           
15308: 2016-06-30 11:22:59,868 INFO  libpurple: proxy:Connection in progress                                                                                                                  
15308: 2016-06-30 11:22:59,868 INFO  libpurple: proxy:Connecting to 192.168.1.1:60000.                                                                                                        
15308: 2016-06-30 11:22:59,868 INFO  libpurple: proxy:Connected to 192.168.1.1:60000.                                                                                                         
15308: 2016-06-30 11:22:59,869 INFO  libpurple: util:request constructed                                                                                                                      
15308: 2016-06-30 11:22:59,870 INFO  libpurple: util:Response headers: 'HTTP/1.1 200 OK                                                                                                       
CONTENT-LENGTH: 4525                                                                                                                                                                          
CONTENT-TYPE: text/xml                                                                                                                                                                        
DATE: Thu, 30 Jun 2016 09:23:01 GMT                                                                                                                                                           
LAST-MODIFIED: Thu, 01 Jan 1970 00:01:27 GMT                                                                                                                                                  
SERVER: Unspecified, UPnP/1.0, SoftAtHome                                                                                                                                                     
X-User-Agent: redsonic                                                                                                                                                                        
CONNECTION: close                                                                                                                                                                             
                                                                                                                                                                                              
'                                                                                                                                                                                             
15308: 2016-06-30 11:22:59,870 INFO  libpurple: util:parsed 4525                                                                                                                              
15308: 2016-06-30 11:22:59,873 ERROR backend: g_log xmlnode_get_child_with_namespace: assertion 'parent != NULL' failed                                                                       
15308: 2016-06-30 11:22:59,873 INFO  libpurple: upnp:parse_description_response(): could not get serviceTypeNode 1                                                                            
15308: 2016-06-30 11:22:59,873 INFO  libpurple: upnp:purple_upnp_parse_description(): control URL is NULL                                                                                     
15308: 2016-06-30 11:23:03,852 INFO  libpurple: util:Writing file prefs.xml to directory /var/lib/spectrum2/telegram.emevth.no-ip.biz                                                         
15308: 2016-06-30 11:23:03,853 INFO  libpurple: util:Writing file /var/lib/spectrum2/telegram.emevth.no-ip.biz/prefs.xml                                                                      
15308: 2016-06-30 11:23:18,117 INFO  backend: Exiting...

**Comment by BenWiederhake** [comment] 2017-04-11 00:00
Duplicate of #245

**Closed by BenWiederhake** 2017-04-11 00:00 UTC
Labels: spectrum
