### ISSUE TITLE
Joining a group chat/removing group chat causes Pidgin to segfault

### ISSUE THREAD

**Issue by hasues** [majn/telegram-purple#127] opened 2015-09-30 20:09 UTC
When using Telegram group chats with the telegram-purple.  If joining a chat, if it is done outside of telegram-purple, it appears that Pidgin/telgram-purple can not handle this join as it does not understand how to recognize a chat and handle this resource.

If one has joined a chat via Pidgin in telgram-purple, if one selects to "Remove the Chat", pidgin removes the chat, but it appears it is not removing the chat via the "Leave" method in Telegram and thus one still receives events from the chat causing Pidgin to segfault.

**Comment by majn** [comment] 2015-09-30 20:29
Join by link?

By "leave" I assume you probably mean the "Delete and exit" method?

**Comment by hasues** [comment] 2015-10-01 18:33
I guess I am mistaken.  I thought I took this:
https://telegram.me/joinchat/01fb53f301b67d3c7a5532908dfa9a89
and used it in Pidgin to create a chat.  Maybe I did it with the official client. I will have to test and see.

I used the leave "Leave" method by selecting the chat in the official client, and expanding it with the right arrow, and in the top right is a label that says "Leave".

In pidgin, I use the "Remove" by right clicking the chat, and selecting "Remove".  That starts causing the issues, because while the chat is removed from Pidgin, one has not left it as one can view that by using the official client.

**Comment by majn** [comment] 2015-10-01 19:47
>I used the leave "Leave" method by selecting the chat in the official client, and expanding it with the right arrow, and in the top right is a label that says "Leave".

I do this by design, cause I don't think that its a good idea to just leave the chat permanently when someone removes the chat from the buddy list as it might come unexpected to many users. 

In other pidgin protocols (XMPP, IRC for example) the chats in the buddy list are more like bookmarks to quickly join a chat and removing them won't have any permanent effect since you can still join them in the roomlist of available chats. Joining / leaving a chat in Pidgin more comparable to opening / closing the chat window.

The roomlist is where you can see all available chat rooms, your buddy list contains bookmarks to quickly open chat rooms (like in other protocols too) and if you want to remove them permanently there is the action "Delete and exit ... " for all chat rooms.

**Comment by majn** [comment] 2015-10-01 19:47
I wasn't able to reproduce the segfault, do you use v1.2.1?

**Comment by hasues** [comment] 2015-10-02 14:21
1.2.0 Beta 3

**Comment by BenWiederhake** [comment] 2016-02-18 22:27
There have been lots of changes since 1.2.0 in that code. Chances are that the bug got fixed or deleted.

Of course, feel free to re-open this issue if you observe anything like it.

**Closed by BenWiederhake** 2016-02-18 22:27 UTC
